In [35]:
from tensorflow.keras.models import load_model
import numpy as np
from tensorflow.keras.preprocessing import image

In [36]:
model = load_model('../cats_and_dogs_classifier.h5')

In [37]:
data = np.load(f'../data/test_images.npy')
y_label = np.load(f'../data/test_labels.npy')

In [38]:
data.shape

(2005, 150, 150, 3)

In [39]:
new_data_without_filler = np.zeros((2005, 150, 150, 3)) # defult was 150,150,3
new_y_label_without_filler = np.zeros(2005, dtype=int)
i = 0
for idx, val in enumerate(y_label):
    new_data_without_filler[i] = data[idx]
    new_y_label_without_filler[i] = y_label[idx]
    i+=1
data = new_data_without_filler
y_label = new_y_label_without_filler

In [40]:
data = data / 255.0

In [41]:
predictions = model.predict(data)

63/63 [==============================] - 5s 71ms/step


In [42]:
predictions

array([[9.9851853e-01],
       [9.2717773e-01],
       [3.4620442e-08],
       ...,
       [3.1597618e-09],
       [2.1929739e-02],
       [1.0000000e+00]], dtype=float32)

In [43]:
def threshold_array(arr, threshold=0.5):
    return np.where(arr > threshold, 1, 0)

In [44]:
predictions = threshold_array(predictions)
predictions

array([[1],
       [1],
       [0],
       ...,
       [0],
       [0],
       [1]])

In [45]:
predictions = predictions.reshape(-1)

In [46]:
predictions

array([1, 1, 0, ..., 0, 0, 1])

In [47]:
y_label

array([0, 0, 0, ..., 1, 1, 1])

In [48]:
def compute_match_percentage(arr1, arr2):
    # Vérifier si les tableaux ont la même forme
    if arr1.shape != arr2.shape:
        return -1
    
    # Calculer le nombre d'éléments correspondants
    match_count = np.sum(arr1 == arr2)
    
    # Calculer le pourcentage de correspondance
    match_percentage = (match_count / arr1.size) * 100.0
    
    return match_percentage

In [49]:
compute_match_percentage(predictions,y_label)

77.25685785536159